import type { StrategyTemplate } from "./strategy-template-card";
import {
    Rocket,
    Sparkles,
    Megaphone,
    FileText,
    ShoppingBag,
    HeartPulse,
    Gem,
    Lightbulb,
    Users,
    MessageCircle,
    Target,
} from "lucide-react";

export type StrategyDomain = "gym" | "jewellery" | "ecommerce";

export const DOMAIN_LABELS: Record<StrategyDomain, string> = {
    gym: "Gym",
    jewellery: "Jewellery",
    ecommerce: "E-commerce",
};

const P = {
    insta_yt_fb: ["instagram", "youtube", "facebook"],
    insta_in: ["instagram", "linkedin"],
    insta_fb_li: ["instagram", "facebook", "linkedin"],
    insta_fb: ["instagram", "facebook"] as string[],
    all: ["instagram", "linkedin", "facebook", "youtube"] as string[],
};

// These are "strategy focus" templates (not just posting schedules).
// They still generate strategy posts under the hood, but the AI prompt is tuned by `strategyType`.
export const DOMAIN_STRATEGY_TEMPLATES: Record<StrategyDomain, StrategyTemplate[]> = {
    gym: [
        {
            id: "gym-social-growth",
            title: "Social Growth Sprint",
            subtitle: "Challenge-proven 30-day growth ideas (inspired by Gymshark-style playbooks)",
            icon: Rocket,
            iconBg: "bg-emerald-100 text-emerald-600",
            prefill: {
                businessType: "Gym",
                goal: "increase_followers",
                strategyType: "social_growth",
                theme: "prebuilt_gym_gym_social_growth",
                platforms: P.insta_fb,
                durationDays: 14,
            },
        },
        {
            id: "gym-marketing-funnel",
            title: "Marketing Funnel Plan",
            subtitle: "Proven funnel-led 30-day plan from awareness to conversion",
            icon: Megaphone,
            iconBg: "bg-blue-100 text-blue-600",
            prefill: {
                businessType: "Gym",
                goal: "brand_awareness",
                strategyType: "marketing_plan",
                theme: "prebuilt_gym_gym_marketing_funnel",
                platforms: P.insta_yt_fb,
                durationDays: 30,
            },
        },
        {
            id: "gym-educational-workouts",
            title: "Educational Workout Library",
            subtitle: "Knowledge-first 30-day authority series inspired by top fitness creators",
            icon: Lightbulb,
            iconBg: "bg-amber-100 text-amber-600",
            prefill: {
                businessType: "Gym",
                goal: "brand_awareness",
                strategyType: "knowledge_based",
                theme: "prebuilt_gym_workout_education_series",
                platforms: P.insta_fb,
                durationDays: 21,
            },
        },
        {
            id: "gym-community-challenges",
            title: "Community Challenge Engine",
            subtitle: "10-day challenge-based engagement ideas with proven UGC loops",
            icon: MessageCircle,
            iconBg: "bg-pink-100 text-pink-600",
            prefill: {
                businessType: "Gym",
                goal: "engagement",
                strategyType: "customer_engagement",
                theme: "prebuilt_gym_community_challenges",
                platforms: P.insta_fb_li,
                durationDays: 14,
            },
        },
        {
            id: "gym-member-retention",
            title: "Member Retention Tips",
            subtitle: "Retention-focused content prompts based on proven gym community practices",
            icon: HeartPulse,
            iconBg: "bg-rose-100 text-rose-600",
            prefill: {
                businessType: "Gym",
                goal: "engagement",
                strategyType: "customer_engagement",
                theme: "prebuilt_gym_retention_support_content",
                platforms: P.insta_fb,
                durationDays: 30,
            },
        },
        {
            id: "gym-class-launch",
            title: "Class Launch Campaign",
            subtitle: "Promote a new class with clear offers & CTAs",
            icon: Rocket,
            iconBg: "bg-indigo-100 text-indigo-600",
            prefill: {
                businessType: "Gym",
                goal: "increase_sales",
                strategyType: "marketing_plan",
                theme: "prebuilt_gym_new_class_launch",
                platforms: P.insta_in,
                durationDays: 14,
            },
        },
        {
            id: "gym-equipment-know-how",
            title: "Equipment Know-How",
            subtitle: "Knowledge-based tips for safer, smarter training",
            icon: Lightbulb,
            iconBg: "bg-amber-100 text-amber-600",
            prefill: {
                businessType: "Gym",
                goal: "brand_awareness",
                strategyType: "knowledge_based",
                theme: "prebuilt_gym_equipment_howto_series",
                platforms: P.insta_fb,
                durationDays: 21,
            },
        },
        {
            id: "gym-ugc-spotlight",
            title: "Member Spotlight (UGC)",
            subtitle: "Turn testimonials into an engagement flywheel",
            icon: Users,
            iconBg: "bg-violet-100 text-violet-600",
            prefill: {
                businessType: "Gym",
                goal: "engagement",
                strategyType: "customer_engagement",
                theme: "prebuilt_gym_member_ugc_spotlight",
                platforms: P.insta_fb,
                durationDays: 14,
            },
        },
        {
            id: "gym-faq-mythbusters",
            title: "FAQ + Mythbusters",
            subtitle: "Educational debunks that people actually share",
            icon: Lightbulb,
            iconBg: "bg-emerald-100 text-emerald-600",
            prefill: {
                businessType: "Gym",
                goal: "brand_awareness",
                strategyType: "knowledge_based",
                theme: "prebuilt_gym_faq_mythbusters",
                platforms: P.insta_yt_fb,
                durationDays: 30,
            },
        },
        {
            id: "gym-offer-cta",
            title: "Offer + CTA Sprint",
            subtitle: "Short, punchy promotions designed for conversion",
            icon: ShoppingBag,
            iconBg: "bg-orange-100 text-orange-600",
            prefill: {
                businessType: "Gym",
                goal: "increase_sales",
                strategyType: "marketing_plan",
                theme: "prebuilt_gym_offer_cta_campaign",
                platforms: P.insta_fb,
                durationDays: 14,
            },
        },
    ],

    jewellery: [
        {
            id: "jewel-social-growth",
            title: "Jewellery Social Growth",
            subtitle: "30-day jewellery growth ideas inspired by proven social-first brands",
            icon: Sparkles,
            iconBg: "bg-fuchsia-100 text-fuchsia-600",
            prefill: {
                businessType: "Jewellery",
                goal: "increase_followers",
                strategyType: "social_growth",
                theme: "prebuilt_jewellery_jewellery_social_growth",
                platforms: P.insta_fb,
                durationDays: 14,
            },
        },
        {
            id: "jewel-marketing-collection-launch",
            title: "Collection Launch Plan",
            subtitle: "Proven launch-style 30-day idea framework for new drops",
            icon: Megaphone,
            iconBg: "bg-blue-100 text-blue-600",
            prefill: {
                businessType: "Jewellery",
                goal: "increase_sales",
                strategyType: "marketing_plan",
                theme: "prebuilt_jewellery_collection_launch",
                platforms: P.insta_in,
                durationDays: 14,
            },
        },
        {
            id: "jewel-care-education",
            title: "Jewellery Care Academy",
            subtitle: "Knowledge-based 30-day trust-building ideas inspired by premium brands",
            icon: Lightbulb,
            iconBg: "bg-amber-100 text-amber-600",
            prefill: {
                businessType: "Jewellery",
                goal: "brand_awareness",
                strategyType: "knowledge_based",
                theme: "prebuilt_jewellery_jewellery_care_howto",
                platforms: P.insta_fb,
                durationDays: 21,
            },
        },
        {
            id: "jewel-style-engagement",
            title: "Style Match Prompts",
            subtitle: "10-day challenge ideas to increase comments, saves, and DMs",
            icon: MessageCircle,
            iconBg: "bg-pink-100 text-pink-600",
            prefill: {
                businessType: "Jewellery",
                goal: "engagement",
                strategyType: "customer_engagement",
                theme: "prebuilt_jewellery_style_match_prompts",
                platforms: P.insta_fb_li,
                durationDays: 14,
            },
        },
        {
            id: "jewel-customer-story",
            title: "Customer Story Loop",
            subtitle: "Proven story-led engagement ideas from customer-driven jewellery creators",
            icon: Users,
            iconBg: "bg-violet-100 text-violet-600",
            prefill: {
                businessType: "Jewellery",
                goal: "engagement",
                strategyType: "customer_engagement",
                theme: "prebuilt_jewellery_customer_story_loop",
                platforms: P.insta_fb,
                durationDays: 30,
            },
        },
        {
            id: "jewel-brand-positioning",
            title: "Brand Positioning Plan",
            subtitle: "Marketing plan that clarifies your value and audience",
            icon: FileText,
            iconBg: "bg-indigo-100 text-indigo-600",
            prefill: {
                businessType: "Jewellery",
                goal: "brand_awareness",
                strategyType: "marketing_plan",
                theme: "prebuilt_jewellery_brand_positioning",
                platforms: P.insta_yt_fb,
                durationDays: 30,
            },
        },
        {
            id: "jewel-material-myths",
            title: "Material Myths (Mythbusters)",
            subtitle: "Knowledge-based debunks for better buying decisions",
            icon: Lightbulb,
            iconBg: "bg-emerald-100 text-emerald-600",
            prefill: {
                businessType: "Jewellery",
                goal: "brand_awareness",
                strategyType: "knowledge_based",
                theme: "prebuilt_jewellery_material_mythbusters",
                platforms: P.insta_fb,
                durationDays: 21,
            },
        },
        {
            id: "jewel-gift-guide-cta",
            title: "Gift Guide + CTA",
            subtitle: "Short campaign built for conversion during seasonal moments",
            icon: Rocket,
            iconBg: "bg-emerald-100 text-emerald-600",
            prefill: {
                businessType: "Jewellery",
                goal: "increase_sales",
                strategyType: "marketing_plan",
                theme: "prebuilt_jewellery_gift_guide_cta",
                platforms: P.insta_fb,
                durationDays: 14,
            },
        },
        {
            id: "jewel-creator-collabs",
            title: "Creator Collab Strategy",
            subtitle: "Customer engagement via partnerships and UGC prompts",
            icon: Target,
            iconBg: "bg-orange-100 text-orange-600",
            prefill: {
                businessType: "Jewellery",
                goal: "engagement",
                strategyType: "customer_engagement",
                theme: "prebuilt_jewellery_creator_collab_strategy",
                platforms: P.insta_fb_li,
                durationDays: 30,
            },
        },
        {
            id: "jewel-care-rituals",
            title: "Care Rituals Series",
            subtitle: "Knowledge-based micro-lessons that drive saves",
            icon: Gem,
            iconBg: "bg-amber-100 text-amber-600",
            prefill: {
                businessType: "Jewellery",
                goal: "brand_awareness",
                strategyType: "knowledge_based",
                theme: "prebuilt_jewellery_care_rituals_series",
                platforms: P.insta_yt_fb,
                durationDays: 21,
            },
        },
    ],

    ecommerce: [
        {
            id: "eco-growth-engine",
            title: "E-commerce Growth Engine",
            subtitle: "30-day e-commerce growth ideas inspired by proven content engines",
            icon: Rocket,
            iconBg: "bg-emerald-100 text-emerald-600",
            prefill: {
                businessType: "Ecommerce",
                goal: "increase_followers",
                strategyType: "social_growth",
                theme: "prebuilt_ecommerce_ecom_growth_engine",
                platforms: P.all,
                durationDays: 14,
            },
        },
        {
            id: "eco-marketing-funnel",
            title: "Full Funnel Marketing Plan",
            subtitle: "Proven 30-day funnel journey from discovery to purchase",
            icon: Megaphone,
            iconBg: "bg-blue-100 text-blue-600",
            prefill: {
                businessType: "Ecommerce",
                goal: "brand_awareness",
                strategyType: "marketing_plan",
                theme: "prebuilt_ecommerce_ecom_full_funnel",
                platforms: P.all,
                durationDays: 30,
            },
        },
        {
            id: "eco-product-education",
            title: "Product Education Series",
            subtitle: "Knowledge-based 30-day content ideas to build trust before selling",
            icon: Lightbulb,
            iconBg: "bg-amber-100 text-amber-600",
            prefill: {
                businessType: "Ecommerce",
                goal: "brand_awareness",
                strategyType: "knowledge_based",
                theme: "prebuilt_ecommerce_product_education_series",
                platforms: P.insta_yt_fb,
                durationDays: 21,
            },
        },
        {
            id: "eco-customer-engagement",
            title: "Customer Engagement Flywheel",
            subtitle: "10-day challenge-style engagement ideas using proven community loops",
            icon: MessageCircle,
            iconBg: "bg-pink-100 text-pink-600",
            prefill: {
                businessType: "Ecommerce",
                goal: "engagement",
                strategyType: "customer_engagement",
                theme: "prebuilt_ecommerce_customer_engagement_flywheel",
                platforms: P.insta_fb_li,
                durationDays: 14,
            },
        },
        {
            id: "eco-offer-launch",
            title: "Offer Launch Campaign",
            subtitle: "Proven short-sprint launch ideas for conversion-focused campaigns",
            icon: ShoppingBag,
            iconBg: "bg-orange-100 text-orange-600",
            prefill: {
                businessType: "Ecommerce",
                goal: "increase_sales",
                strategyType: "marketing_plan",
                theme: "prebuilt_ecommerce_offer_launch_campaign",
                platforms: P.insta_fb,
                durationDays: 14,
            },
        },
        {
            id: "eco-brand-story",
            title: "Brand Story & Values",
            subtitle: "Build affinity with narrative-led content and CTAs",
            icon: FileText,
            iconBg: "bg-indigo-100 text-indigo-600",
            prefill: {
                businessType: "Ecommerce",
                goal: "brand_awareness",
                strategyType: "marketing_plan",
                theme: "prebuilt_ecommerce_brand_story_values",
                platforms: P.insta_fb_li,
                durationDays: 30,
            },
        },
        {
            id: "eco-faq-objections",
            title: "FAQ + Objection Handling",
            subtitle: "Knowledge-based answers that increase trust and conversion",
            icon: Lightbulb,
            iconBg: "bg-emerald-100 text-emerald-600",
            prefill: {
                businessType: "Ecommerce",
                goal: "brand_awareness",
                strategyType: "knowledge_based",
                theme: "prebuilt_ecommerce_faq_objection_handling",
                platforms: P.all,
                durationDays: 21,
            },
        },
        {
            id: "eco-ugc-testimonials",
            title: "UGC Testimonials Loop",
            subtitle: "Turn customers into creators with repeatable prompts",
            icon: Users,
            iconBg: "bg-violet-100 text-violet-600",
            prefill: {
                businessType: "Ecommerce",
                goal: "engagement",
                strategyType: "customer_engagement",
                theme: "prebuilt_ecommerce_ugc_testimonials_loop",
                platforms: P.insta_fb,
                durationDays: 14,
            },
        },
        {
            id: "eco-cross-sell-push",
            title: "Cross-sell Campaign",
            subtitle: "Marketing plan for bundling, add-ons, and upsells",
            icon: Target,
            iconBg: "bg-blue-100 text-blue-600",
            prefill: {
                businessType: "Ecommerce",
                goal: "increase_sales",
                strategyType: "marketing_plan",
                theme: "prebuilt_ecommerce_cross_sell_upsell",
                platforms: P.insta_fb_li,
                durationDays: 21,
            },
        },
        {
            id: "eco-saves-and-share",
            title: "Save-worthy Share Campaign",
            subtitle: "Social growth focused on content people want to bookmark",
            icon: Sparkles,
            iconBg: "bg-amber-100 text-amber-600",
            prefill: {
                businessType: "Ecommerce",
                goal: "increase_followers",
                strategyType: "social_growth",
                theme: "prebuilt_ecommerce_saves_and_share_campaign",
                platforms: P.insta_fb,
                durationDays: 14,
            },
        },
    ],
};

