export const PRESET_TEMPLATES = [
  {
    id: 'sale-poster',
    name: 'Summer Sale',
    thumbnail: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=200&q=80',
    json_data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1080,
          height: 1080,
          fill: '#fef3c7',
          selectable: false,
        },
        {
          type: 'i-text',
          left: 540,
          top: 300,
          text: 'SUMMER',
          fontSize: 120,
          fontWeight: 'bold',
          fill: '#92400e',
          originX: 'center',
          fontFamily: 'Inter',
        },
        {
          type: 'i-text',
          left: 540,
          top: 450,
          text: 'SALE',
          fontSize: 200,
          fontWeight: '900',
          fill: '#92400e',
          originX: 'center',
          fontFamily: 'Inter',
        },
        {
          type: 'i-text',
          left: 540,
          top: 700,
          text: 'UP TO 50% OFF',
          fontSize: 60,
          fontWeight: 'bold',
          fill: '#ffffff',
          backgroundColor: '#92400e',
          originX: 'center',
          fontFamily: 'Inter',
        }
      ],
    },
  },
  {
    id: 'product-launch',
    name: 'New Arrival',
    thumbnail: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=200&q=80',
    json_data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1080,
          height: 1080,
          fill: '#18181b',
          selectable: false,
        },
        {
          type: 'i-text',
          left: 100,
          top: 100,
          text: 'NEW\nARRIVAL',
          fontSize: 100,
          fontWeight: 'bold',
          fill: '#ffffff',
          fontFamily: 'Inter',
        },
        {
          type: 'rect',
          left: 100,
          top: 350,
          width: 880,
          height: 500,
          fill: '#27272a',
          rx: 20,
          ry: 20,
        },
        {
          type: 'i-text',
          left: 540,
          top: 900,
          text: 'SHOP NOW AT AGENT-ELEPHANT.COM',
          fontSize: 30,
          fill: '#f2d412',
          originX: 'center',
          fontFamily: 'Inter',
        }
      ],
    },
  }
];
